import os

import py_trees
import pytest

from utama_core.config.formations import FormationType, get_formations
from utama_core.entities.game.field import FieldBounds
from utama_core.global_utils.mapping_utils import map_left_right_to_colors
from utama_core.run.strategy_runner import StrategyRunner
from utama_core.strategy.common.abstract_strategy import AbstractStrategy
from utama_core.tests.common.abstract_test_manager import (
    AbstractTestManager,
    TestingStatus,
)

os.environ["SDL_VIDEO_WINDOW_POS"] = "100,100"

POSITION_TOLERANCE = 0.15


class _IdleStrategy(AbstractStrategy):
    """Minimal strategy used only to drive runner lifecycle."""

    exp_ball: bool = True

    def create_behaviour_tree(self) -> py_trees.behaviour.Behaviour:
        return py_trees.behaviours.Success(name="Idle")

    def assert_exp_robots(self, n_runtime_friendly: int, n_runtime_enemy: int) -> bool:
        return True

    def assert_exp_goals(self, includes_my_goal_line: bool, includes_opp_goal_line: bool) -> bool:
        return True

    def get_min_bounding_req(self):
        return None


class _CaptureFirstFrameManager(AbstractTestManager):
    n_episodes = 1

    def __init__(self):
        super().__init__()
        self.friendly_positions: dict[int, tuple[float, float]] = {}
        self.enemy_positions: dict[int, tuple[float, float]] = {}
        self.ball_position: tuple[float, float] | None = None

    def reset_field(self, sim_controller, game):
        # Keep RSIM initial spawn positions generated by the formation allocator.
        return None

    def eval_status(self, game):
        if not self.friendly_positions:
            self.friendly_positions = {rid: (robot.p.x, robot.p.y) for rid, robot in game.friendly_robots.items()}
            self.enemy_positions = {rid: (robot.p.x, robot.p.y) for rid, robot in game.enemy_robots.items()}
            if game.ball is not None:
                self.ball_position = (game.ball.p.x, game.ball.p.y)
        return TestingStatus.SUCCESS


@pytest.mark.parametrize(
    "team_is_yellow,team_on_right,n_friendly,n_enemy",
    [
        (True, False, 3, 1),
        (False, True, 3, 1),
    ],
)
def test_rsim_formation_allocation_and_spawn_positions(
    team_is_yellow: bool,
    team_on_right: bool,
    n_friendly: int,
    n_enemy: int,
):
    runner = StrategyRunner(
        strategy=_IdleStrategy(),
        my_team_is_yellow=team_is_yellow,
        my_team_is_right=team_on_right,
        mode="rsim",
        exp_friendly=n_friendly,
        exp_enemy=n_enemy,
    )

    left_start, right_start = get_formations(
        bounds=runner.field_bounds,
        n_left=n_enemy if team_on_right else n_friendly,
        n_right=n_friendly if team_on_right else n_enemy,
        formation_type=FormationType.START_ONE,
    )
    expected_yellow, expected_blue = map_left_right_to_colors(
        team_is_yellow,
        team_on_right,
        right_start,
        left_start,
    )

    # Allocation behavior in StrategyRunner._load_sim
    assert runner.rsim_env.yellow_formation == expected_yellow
    assert runner.rsim_env.blue_formation == expected_blue

    manager = _CaptureFirstFrameManager()
    passed = runner.run_test(manager, episode_timeout=5.0, rsim_headless=True)
    assert passed

    expected_friendly = expected_yellow if team_is_yellow else expected_blue
    expected_enemy = expected_blue if team_is_yellow else expected_yellow

    assert len(manager.friendly_positions) == n_friendly
    assert len(manager.enemy_positions) == n_enemy

    for rid, expected in enumerate(expected_friendly):
        actual_x, actual_y = manager.friendly_positions[rid]
        assert abs(actual_x - expected.x) <= POSITION_TOLERANCE
        assert abs(actual_y - expected.y) <= POSITION_TOLERANCE

    for rid, expected in enumerate(expected_enemy):
        actual_x, actual_y = manager.enemy_positions[rid]
        assert abs(actual_x - expected.x) <= POSITION_TOLERANCE
        assert abs(actual_y - expected.y) <= POSITION_TOLERANCE


def test_rsim_spawn_respects_shifted_bounds_and_ball_center():
    shifted_bounds = FieldBounds(top_left=(1.5, 2.0), bottom_right=(4.5, -2.0))

    runner = StrategyRunner(
        strategy=_IdleStrategy(),
        my_team_is_yellow=True,
        my_team_is_right=False,
        mode="rsim",
        exp_friendly=1,
        exp_enemy=0,
        field_bounds=shifted_bounds,
    )

    manager = _CaptureFirstFrameManager()
    passed = runner.run_test(manager, episode_timeout=5.0, rsim_headless=True)
    assert passed

    expected_x, expected_y = shifted_bounds.center
    assert manager.ball_position is not None
    assert abs(manager.ball_position[0] - expected_x) <= POSITION_TOLERANCE
    assert abs(manager.ball_position[1] - expected_y) <= POSITION_TOLERANCE
