repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
        files: \.py$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261  # replace with latest stable version
    hooks:
      - id: ruff
        args: ["--fix"]  # auto-fix issues like formatting, unused imports
        additional_dependencies: []
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # replace with latest stable version
    hooks:
      - id: isort
        args: ["--profile", "black"]  # optional, use your formatting style
        files: \.py$

  - repo: https://github.com/myint/docformatter
    rev: v1.7.7  # replace with latest stable version
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-summaries", "120", "--wrap-descriptions", "120"]
        files: \.py$
