[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Utama"
version = "1.0.0"
description = "Imperial RoboCup SSL 25 Software Algorithms Codebase."
authors = [
    { name = "Fred Huang", email = "fred.huang23@imperial.ac.uk" }
]
requires-python = ">=3.11"

[tool.setuptools]
py-modules = []
packages = ["strategy", "entities", "global_utils", "motion_planning", "skills", "rsoccer_simulator", "team_controller", "config", "run", "test"]