[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Utama"
version = "1.0.0"
description = "Imperial RoboCup SSL 25 Software Algorithms Codebase."
readme = "README.md"
authors = [
    { name = "Joel Ng", email = "zhi-ming.ng22@imperial.ac.uk" },
    { name = "Fred Huang", email = "fred.huang23@imperial.ac.uk" }
]

dependencies = [
    "numpy == 2.0.2",
    "gymnasium == 1.0.0",
    "pygame == 2.6.1",
    "protobuf == 3.20.2",
    "shapely == 2.0.6",
    "gymnasium >= 0.28.1",
    "rc-robosim >= 1.2.0",
    "pygame >= 2.1.3",
]
requires-python = ">=3.9,<3.11"

[tool.setuptools]
py-modules = []