[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Utama"
version = "1.0.0"
description = "Imperial RoboCup SSL 25 Software Algorithms Codebase."
readme = "README.md"
authors = [
    { name = "Fred Huang", email = "fred.huang23@imperial.ac.uk" },
    { name = "Joel Ng", email = "zhi-ming.ng22@imperial.ac.uk" },
    { name = "Isaac Yong",  email = "isaac.yong24@imperial.ac.uk" },
    { name = "Hamish Starling", email = "hamish.starling22@imperial.ac.uk" },
    { name = "Luke Moran", email = "luke.moran22@imperial.ac.uk" },
    { name = "Sadig Sadikhzada", email = "sadig.sadikhzada23@imperial.ac.uk" },
    { name = "Li Han", email = "han.li124@imperial.ac.uk" }
]

dependencies = [
    "numpy == 2.0.2",
    "pygame == 2.6.1",
    "protobuf == 3.20.2",
    "shapely == 2.0.6",
    "gymnasium == 1.0.0",
    "rc-robosim == 1.2",
    "pygame == 2.6.1",
    "pyserial == 3.5",
    "pytest == 8.3.4",
    "lenses>=1.2.0",
    "py-trees>=2.3.0",
]
requires-python = ">=3.9,<3.11"

[tool.setuptools]
py-modules = []
packages = ["strategy", "entities", "global_utils", "motion_planning", "skills", "rsoccer_simulator", "team_controller", "config", "run", "test"]

[dependency-groups]
dev = [
    "ruff>=0.9.8",
]

[tool.ruff]
extend-exclude = [
    "*_pb2.py" # Ignore files matching a pattern
]

[tool.ruff.lint]
ignore = [
    "F401",  # Module imported but unused
]
