from utama_core.entities.game.field import Field

BALL_KEEP_OUT_DISTANCE = 0.55
BALL_PLACEMENT_DONE_DISTANCE = 0.15
OPPONENT_DEFENSE_AREA_KEEP_DISTANCE = 0.25
PENALTY_BEHIND_MARK_DISTANCE = 0.4
PENALTY_MARK_HALF_FIELD_RATIO = 0.5
CLEARANCE_FALLBACK_DIRECTION = (1.0, 0.0)

PENALTY_LINE_Y_STEP_RATIO = 0.35 / Field.FULL_FIELD_HALF_WIDTH

KICKOFF_SUPPORT_POSITION_RATIOS_OWN_HALF = (
    (0.8 / Field.FULL_FIELD_HALF_LENGTH, 0.5 / Field.FULL_FIELD_HALF_WIDTH),
    (0.8 / Field.FULL_FIELD_HALF_LENGTH, -0.5 / Field.FULL_FIELD_HALF_WIDTH),
    (1.5 / Field.FULL_FIELD_HALF_LENGTH, 0.8 / Field.FULL_FIELD_HALF_WIDTH),
    (1.5 / Field.FULL_FIELD_HALF_LENGTH, -0.8 / Field.FULL_FIELD_HALF_WIDTH),
    (2.5 / Field.FULL_FIELD_HALF_LENGTH, 0.0),
)

KICKOFF_DEFENCE_POSITION_RATIOS_OWN_HALF = (
    (0.8 / Field.FULL_FIELD_HALF_LENGTH, 0.4 / Field.FULL_FIELD_HALF_WIDTH),
    (0.8 / Field.FULL_FIELD_HALF_LENGTH, -0.4 / Field.FULL_FIELD_HALF_WIDTH),
    (1.5 / Field.FULL_FIELD_HALF_LENGTH, 0.6 / Field.FULL_FIELD_HALF_WIDTH),
    (1.5 / Field.FULL_FIELD_HALF_LENGTH, -0.6 / Field.FULL_FIELD_HALF_WIDTH),
    (2.5 / Field.FULL_FIELD_HALF_LENGTH, 0.0),
    (1.5 / Field.FULL_FIELD_HALF_LENGTH, 0.0),
)
