from utama_core.config.physical_constants import ROBOT_RADIUS


class fastpathplanningconfig:
    ROBOT_DIAMETER = 2 * ROBOT_RADIUS
    OBSTACLE_CLEARANCE = ROBOT_DIAMETER * 1.5
    SUBGOAL_DISTANCE = OBSTACLE_CLEARANCE * 1.1
    LOOK_AHEAD_RANGE = 3
    MAXRECURSION_LENGTH = 3
    PROJECTEDFRAMES = 15
