def test_velocity_calculation_correct_for_ball
def test_velocity_calculation_correct_for_enemy_robot
def test_velocity_calculation_correct_for_friendly_robot
def test_returns_not_moving_if_not_enough_information_for_velocity
def test_complete_refining_refines_correctly
def test_acceleration_calculation_implements_expected_formula
def test_extraction_of_velocity_time_pairs
 