# .github/workflows/bump_version.yml
name: Bump Version

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          cache: true

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Install toml-cli for file editing
        run: pip install toml-cli

      - name: Bump version and sync files
        run: |
          # 1. This command will now correctly edit utama_core/__init__.py
          pixi run hatch version patch

          # 2. Get the new version from the single source of truth (the __init__.py file)
          #    This command finds the line with __version__ and extracts the string in quotes.
          NEW_VERSION=$(grep '__version__' utama_core/__init__.py | cut -d '"' -f 2)
          echo "New version: $NEW_VERSION"

          # 3. Update the pixi.toml file with the new version
          toml set --toml-path pixi.toml workspace.version "$NEW_VERSION"
          toml set --toml-path pixi.toml package.version "$NEW_VERSION"

      - name: Commit version bump to PR branch
        run: |
          git add pyproject.toml pixi.toml utama_core/__init__.py
          if ! git diff --staged --quiet; then
            NEW_VERSION=$(grep '__version__' utama_core/__init__.py | cut -d '"' -f 2)
            git commit -m "chore(release): bump version to v$NEW_VERSION"
            
            # Push to the PR branch using GITHUB_HEAD_REF
            git push origin HEAD:${GITHUB_HEAD_REF}
          else
            echo "No version changes to commit."
          fi
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}

