name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pixi
        run: curl -fsSL https://pixi.sh/install.sh | sh

      - name: Install dependencies
        run: |
          curl -fsSL https://pixi.sh/install.sh | sh
          pixi install
          pixi shell

      - name: Run tests
        run: |
          if [[ $GITHUB_EVENT_NAME == "push" ]]; then
            pytest test/ --level full --ignore-glob "**/*grsim*" --headless --junit-xml=test-results.xml
          elif [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            pytest test/ --level quick --ignore-glob "**/*grsim*" --headless --junit-xml=test-results.xml
          fi


      - name: Test Report
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: RSoccer CI Test Results
