name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: true

      - name: Run tests
        run: |
          if [[ $GITHUB_EVENT_NAME == "push" ]]; then
            pixi run -- pytest test/ --level full --ignore-glob "**/*grsim*" --headless --junit-xml=test-results.xml
          elif [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            pixi run -- pytest test/ --level quick --ignore-glob "**/*grsim*" --headless --junit-xml=test-results.xml
          fi


      - name: Test Report
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: RSoccer CI Test Results
